services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: node server.js
    labels:
      - "traefik.http.routers.wat.rule=Host(`wat.peciak.xyz`)"
      - "traefik.http.routers.wat.tls.certresolver=letsencrypt"