name: Docker build & push image

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: Deploy to seelf
        uses: YuukanOO/seelf-deploy-action@v1
        with:
          host: ${{ secrets.SEELF_URL }}
          token: ${{ secrets.SEELF_TOKEN }}
          appid: ${{ secrets.SEELF_APPID }}
      - name: Output URL
        run: echo "Check it out at ${{ steps.deploy.outputs.url }}"